# Generated by Django 3.1.7 on 2021-03-25 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20210322_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 7, 28, 10, 665733, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
